export const iconPokemon = new Map();
iconPokemon.set("grass", "../assets/types/grass.svg");
iconPokemon.set("bug", "../assets/types/bug.svg");
iconPokemon.set("dark", "../assets/types/dark.svg");
iconPokemon.set("dragon", "../assets/types/dragon.svg");
iconPokemon.set("electric", "../assets/types/electric.svg");
iconPokemon.set("fairy", "../assets/types/fairy.svg");
iconPokemon.set("fighting", "../assets/types/fighting.svg");
iconPokemon.set("fire", "../assets/types/fire.svg");
iconPokemon.set("flying", "../assets/types/flying.svg");
iconPokemon.set("ghost", "../assets/types/ghost.svg");
iconPokemon.set("ground", "../assets/types/ground.svg");
iconPokemon.set("ice", "../assets/types/ice.svg");
iconPokemon.set("normal", "../assets/types/normal.svg");
iconPokemon.set("poison", "../assets/types/poison.svg");
iconPokemon.set("psychic", "../assets/types/psychic.svg");
iconPokemon.set("rock", "../assets/types/rock.svg");
iconPokemon.set("steel", "../assets/types/steel.svg");
iconPokemon.set("water", "../assets/types/water.svg");

export default { iconPokemon };
